/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FieldToSend, Score } from "./apps/scoring-manager/scoring.interface";
import { IModal } from "./libs/modal";
import { StyleEventDetail } from "./shared/scx-radio-group/scx-radio-button/scx-radio-button";
import { RadioGroupChangeEventDetail } from "./shared/scx-radio-group/scx-radio-group";
export { FieldToSend, Score } from "./apps/scoring-manager/scoring.interface";
export { IModal } from "./libs/modal";
export { StyleEventDetail } from "./shared/scx-radio-group/scx-radio-button/scx-radio-button";
export { RadioGroupChangeEventDetail } from "./shared/scx-radio-group/scx-radio-group";
export namespace Components {
    interface AddModel {
    }
    interface AddScore {
        "addNewField"?: boolean;
        /**
          * @default {     id: 0,     name: '',     type: '',     weight: 0,     scores: [],   }
         */
        "field": FieldToSend;
        /**
          * @default 0
         */
        "fieldIndex": number;
        "scope": 'Contactability' | 'Propensity';
    }
    interface MovableRowsTable {
    }
    interface ScoreField {
        "editMode": boolean;
        "field": FieldToSend;
        "nScore": number;
        "switch"?: 1 | 3 | null;
    }
    interface ScorePanel {
        "scope": 'Contactability' | 'Propensity';
    }
    interface ScxEmptyState {
        "esTitle"?: string;
        "icon": string;
        "label"?: string;
    }
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface ScxExampleComponents {
    }
    interface ScxIconsExample {
    }
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface ScxModalExample {
        /**
          * @default 'This is an example modal component.'
         */
        "message": string;
        "modal": IModal;
        /**
          * @default 'Example Modal'
         */
        "modalTitle": string;
    }
    interface ScxRadioButton {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default this.inputId
         */
        "name": string;
        "value"?: unknown;
    }
    interface ScxRadioGroup {
        /**
          * If `true`, the radios can be deselected.
          * @default false
         */
        "allowEmptySelection": boolean;
        /**
          * The size variant of the radio group. With hug each button accords its size to its content.
          * @default 'fill'
         */
        "contain": 'fill' | 'hug';
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name": string;
        /**
          * The size of the radio buttons.
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The value of the radio group.
         */
        "value"?: unknown | null;
        /**
          * The color variant of the radio group.
          * @default 'default'
         */
        "variant": 'default' | 'neutral' | 'light';
    }
    interface ScxRoot {
        /**
          * @default ''
         */
        "apiUrl": string;
    }
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface ScxTabulatorExample {
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }
}
export interface AddScoreCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAddScoreElement;
}
export interface MovableRowsTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMovableRowsTableElement;
}
export interface ScoreFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScoreFieldElement;
}
export interface ScxEmptyStateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScxEmptyStateElement;
}
export interface ScxRadioButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScxRadioButtonElement;
}
export interface ScxRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScxRadioGroupElement;
}
declare global {
    interface HTMLAddModelElement extends Components.AddModel, HTMLStencilElement {
    }
    var HTMLAddModelElement: {
        prototype: HTMLAddModelElement;
        new (): HTMLAddModelElement;
    };
    interface HTMLAddScoreElementEventMap {
        "addField": FieldToSend;
        "deleteField": number;
        "editField": { field: FieldToSend; key: number };
        "closeNewDialog": any;
    }
    interface HTMLAddScoreElement extends Components.AddScore, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAddScoreElementEventMap>(type: K, listener: (this: HTMLAddScoreElement, ev: AddScoreCustomEvent<HTMLAddScoreElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAddScoreElementEventMap>(type: K, listener: (this: HTMLAddScoreElement, ev: AddScoreCustomEvent<HTMLAddScoreElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAddScoreElement: {
        prototype: HTMLAddScoreElement;
        new (): HTMLAddScoreElement;
    };
    interface HTMLMovableRowsTableElementEventMap {
        "changePage": string;
    }
    interface HTMLMovableRowsTableElement extends Components.MovableRowsTable, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMovableRowsTableElementEventMap>(type: K, listener: (this: HTMLMovableRowsTableElement, ev: MovableRowsTableCustomEvent<HTMLMovableRowsTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMovableRowsTableElementEventMap>(type: K, listener: (this: HTMLMovableRowsTableElement, ev: MovableRowsTableCustomEvent<HTMLMovableRowsTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMovableRowsTableElement: {
        prototype: HTMLMovableRowsTableElement;
        new (): HTMLMovableRowsTableElement;
    };
    interface HTMLScoreFieldElementEventMap {
        "editScore": Score;
        "deleteScore": number;
        "editCheck": 1 | 3 | null;
    }
    interface HTMLScoreFieldElement extends Components.ScoreField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScoreFieldElementEventMap>(type: K, listener: (this: HTMLScoreFieldElement, ev: ScoreFieldCustomEvent<HTMLScoreFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScoreFieldElementEventMap>(type: K, listener: (this: HTMLScoreFieldElement, ev: ScoreFieldCustomEvent<HTMLScoreFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScoreFieldElement: {
        prototype: HTMLScoreFieldElement;
        new (): HTMLScoreFieldElement;
    };
    interface HTMLScorePanelElement extends Components.ScorePanel, HTMLStencilElement {
    }
    var HTMLScorePanelElement: {
        prototype: HTMLScorePanelElement;
        new (): HTMLScorePanelElement;
    };
    interface HTMLScxEmptyStateElementEventMap {
        "iconClick": void;
    }
    interface HTMLScxEmptyStateElement extends Components.ScxEmptyState, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScxEmptyStateElementEventMap>(type: K, listener: (this: HTMLScxEmptyStateElement, ev: ScxEmptyStateCustomEvent<HTMLScxEmptyStateElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScxEmptyStateElementEventMap>(type: K, listener: (this: HTMLScxEmptyStateElement, ev: ScxEmptyStateCustomEvent<HTMLScxEmptyStateElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScxEmptyStateElement: {
        prototype: HTMLScxEmptyStateElement;
        new (): HTMLScxEmptyStateElement;
    };
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface HTMLScxExampleComponentsElement extends Components.ScxExampleComponents, HTMLStencilElement {
    }
    var HTMLScxExampleComponentsElement: {
        prototype: HTMLScxExampleComponentsElement;
        new (): HTMLScxExampleComponentsElement;
    };
    interface HTMLScxIconsExampleElement extends Components.ScxIconsExample, HTMLStencilElement {
    }
    var HTMLScxIconsExampleElement: {
        prototype: HTMLScxIconsExampleElement;
        new (): HTMLScxIconsExampleElement;
    };
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface HTMLScxModalExampleElement extends Components.ScxModalExample, HTMLStencilElement {
    }
    var HTMLScxModalExampleElement: {
        prototype: HTMLScxModalExampleElement;
        new (): HTMLScxModalExampleElement;
    };
    interface HTMLScxRadioButtonElementEventMap {
        "smStyle": StyleEventDetail;
        "smSelect": { checked: boolean; value: unknown };
        "smDeselect": void;
    }
    interface HTMLScxRadioButtonElement extends Components.ScxRadioButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(type: K, listener: (this: HTMLScxRadioButtonElement, ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(type: K, listener: (this: HTMLScxRadioButtonElement, ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScxRadioButtonElement: {
        prototype: HTMLScxRadioButtonElement;
        new (): HTMLScxRadioButtonElement;
    };
    interface HTMLScxRadioGroupElementEventMap {
        "smChange": RadioGroupChangeEventDetail;
    }
    interface HTMLScxRadioGroupElement extends Components.ScxRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(type: K, listener: (this: HTMLScxRadioGroupElement, ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(type: K, listener: (this: HTMLScxRadioGroupElement, ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScxRadioGroupElement: {
        prototype: HTMLScxRadioGroupElement;
        new (): HTMLScxRadioGroupElement;
    };
    interface HTMLScxRootElement extends Components.ScxRoot, HTMLStencilElement {
    }
    var HTMLScxRootElement: {
        prototype: HTMLScxRootElement;
        new (): HTMLScxRootElement;
    };
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface HTMLScxTabulatorExampleElement extends Components.ScxTabulatorExample, HTMLStencilElement {
    }
    var HTMLScxTabulatorExampleElement: {
        prototype: HTMLScxTabulatorExampleElement;
        new (): HTMLScxTabulatorExampleElement;
    };
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface HTMLSmilecxOutboundManagerElement extends Components.SmilecxOutboundManager, HTMLStencilElement {
    }
    var HTMLSmilecxOutboundManagerElement: {
        prototype: HTMLSmilecxOutboundManagerElement;
        new (): HTMLSmilecxOutboundManagerElement;
    };
    interface HTMLElementTagNameMap {
        "add-model": HTMLAddModelElement;
        "add-score": HTMLAddScoreElement;
        "movable-rows-table": HTMLMovableRowsTableElement;
        "score-field": HTMLScoreFieldElement;
        "score-panel": HTMLScorePanelElement;
        "scx-empty-state": HTMLScxEmptyStateElement;
        "scx-example-components": HTMLScxExampleComponentsElement;
        "scx-icons-example": HTMLScxIconsExampleElement;
        "scx-modal-example": HTMLScxModalExampleElement;
        "scx-radio-button": HTMLScxRadioButtonElement;
        "scx-radio-group": HTMLScxRadioGroupElement;
        "scx-root": HTMLScxRootElement;
        "scx-tabulator-example": HTMLScxTabulatorExampleElement;
        "smilecx-outbound-manager": HTMLSmilecxOutboundManagerElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface AddModel {
    }
    interface AddScore {
        "addNewField"?: boolean;
        /**
          * @default {     id: 0,     name: '',     type: '',     weight: 0,     scores: [],   }
         */
        "field"?: FieldToSend;
        /**
          * @default 0
         */
        "fieldIndex"?: number;
        "onAddField"?: (event: AddScoreCustomEvent<FieldToSend>) => void;
        "onCloseNewDialog"?: (event: AddScoreCustomEvent<any>) => void;
        "onDeleteField"?: (event: AddScoreCustomEvent<number>) => void;
        "onEditField"?: (event: AddScoreCustomEvent<{ field: FieldToSend; key: number }>) => void;
        "scope": 'Contactability' | 'Propensity';
    }
    interface MovableRowsTable {
        "onChangePage"?: (event: MovableRowsTableCustomEvent<string>) => void;
    }
    interface ScoreField {
        "editMode": boolean;
        "field": FieldToSend;
        "nScore": number;
        "onDeleteScore"?: (event: ScoreFieldCustomEvent<number>) => void;
        "onEditCheck"?: (event: ScoreFieldCustomEvent<1 | 3 | null>) => void;
        "onEditScore"?: (event: ScoreFieldCustomEvent<Score>) => void;
        "switch"?: 1 | 3 | null;
    }
    interface ScorePanel {
        "scope": 'Contactability' | 'Propensity';
    }
    interface ScxEmptyState {
        "esTitle"?: string;
        "icon": string;
        "label"?: string;
        "onIconClick"?: (event: ScxEmptyStateCustomEvent<void>) => void;
    }
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface ScxExampleComponents {
    }
    interface ScxIconsExample {
    }
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface ScxModalExample {
        /**
          * @default 'This is an example modal component.'
         */
        "message"?: string;
        "modal": IModal;
        /**
          * @default 'Example Modal'
         */
        "modalTitle"?: string;
    }
    interface ScxRadioButton {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default this.inputId
         */
        "name"?: string;
        "onSmDeselect"?: (event: ScxRadioButtonCustomEvent<void>) => void;
        "onSmSelect"?: (event: ScxRadioButtonCustomEvent<{ checked: boolean; value: unknown }>) => void;
        "onSmStyle"?: (event: ScxRadioButtonCustomEvent<StyleEventDetail>) => void;
        "value"?: unknown;
    }
    interface ScxRadioGroup {
        /**
          * If `true`, the radios can be deselected.
          * @default false
         */
        "allowEmptySelection"?: boolean;
        /**
          * The size variant of the radio group. With hug each button accords its size to its content.
          * @default 'fill'
         */
        "contain"?: 'fill' | 'hug';
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name"?: string;
        /**
          * Emitted when the value has changed.
         */
        "onSmChange"?: (event: ScxRadioGroupCustomEvent<RadioGroupChangeEventDetail>) => void;
        /**
          * The size of the radio buttons.
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The value of the radio group.
         */
        "value"?: unknown | null;
        /**
          * The color variant of the radio group.
          * @default 'default'
         */
        "variant"?: 'default' | 'neutral' | 'light';
    }
    interface ScxRoot {
        /**
          * @default ''
         */
        "apiUrl"?: string;
    }
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface ScxTabulatorExample {
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }

    interface AddScoreAttributes {
        "addNewField": boolean;
        "fieldIndex": number;
        "scope": 'Contactability' | 'Propensity';
    }
    interface ScoreFieldAttributes {
        "editMode": boolean;
        "nScore": number;
        "switch": 1 | 3 | null;
    }
    interface ScorePanelAttributes {
        "scope": 'Contactability' | 'Propensity';
    }
    interface ScxEmptyStateAttributes {
        "icon": string;
        "label": string;
        "esTitle": string;
    }
    interface ScxModalExampleAttributes {
        "modalTitle": string;
        "message": string;
    }
    interface ScxRadioButtonAttributes {
        "name": string;
        "disabled": boolean;
        "checked": boolean;
    }
    interface ScxRadioGroupAttributes {
        "allowEmptySelection": boolean;
        "name": string;
        "size": 'small' | 'medium' | 'large';
        "contain": 'fill' | 'hug';
        "variant": 'default' | 'neutral' | 'light';
    }
    interface ScxRootAttributes {
        "apiUrl": string;
    }

    interface IntrinsicElements {
        "add-model": AddModel;
        "add-score": Omit<AddScore, keyof AddScoreAttributes> & { [K in keyof AddScore & keyof AddScoreAttributes]?: AddScore[K] } & { [K in keyof AddScore & keyof AddScoreAttributes as `attr:${K}`]?: AddScoreAttributes[K] } & { [K in keyof AddScore & keyof AddScoreAttributes as `prop:${K}`]?: AddScore[K] } & OneOf<"scope", AddScore["scope"], AddScoreAttributes["scope"]>;
        "movable-rows-table": MovableRowsTable;
        "score-field": Omit<ScoreField, keyof ScoreFieldAttributes> & { [K in keyof ScoreField & keyof ScoreFieldAttributes]?: ScoreField[K] } & { [K in keyof ScoreField & keyof ScoreFieldAttributes as `attr:${K}`]?: ScoreFieldAttributes[K] } & { [K in keyof ScoreField & keyof ScoreFieldAttributes as `prop:${K}`]?: ScoreField[K] } & OneOf<"editMode", ScoreField["editMode"], ScoreFieldAttributes["editMode"]> & OneOf<"nScore", ScoreField["nScore"], ScoreFieldAttributes["nScore"]>;
        "score-panel": Omit<ScorePanel, keyof ScorePanelAttributes> & { [K in keyof ScorePanel & keyof ScorePanelAttributes]?: ScorePanel[K] } & { [K in keyof ScorePanel & keyof ScorePanelAttributes as `attr:${K}`]?: ScorePanelAttributes[K] } & { [K in keyof ScorePanel & keyof ScorePanelAttributes as `prop:${K}`]?: ScorePanel[K] } & OneOf<"scope", ScorePanel["scope"], ScorePanelAttributes["scope"]>;
        "scx-empty-state": Omit<ScxEmptyState, keyof ScxEmptyStateAttributes> & { [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes]?: ScxEmptyState[K] } & { [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes as `attr:${K}`]?: ScxEmptyStateAttributes[K] } & { [K in keyof ScxEmptyState & keyof ScxEmptyStateAttributes as `prop:${K}`]?: ScxEmptyState[K] } & OneOf<"icon", ScxEmptyState["icon"], ScxEmptyStateAttributes["icon"]>;
        "scx-example-components": ScxExampleComponents;
        "scx-icons-example": ScxIconsExample;
        "scx-modal-example": Omit<ScxModalExample, keyof ScxModalExampleAttributes> & { [K in keyof ScxModalExample & keyof ScxModalExampleAttributes]?: ScxModalExample[K] } & { [K in keyof ScxModalExample & keyof ScxModalExampleAttributes as `attr:${K}`]?: ScxModalExampleAttributes[K] } & { [K in keyof ScxModalExample & keyof ScxModalExampleAttributes as `prop:${K}`]?: ScxModalExample[K] };
        "scx-radio-button": Omit<ScxRadioButton, keyof ScxRadioButtonAttributes> & { [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes]?: ScxRadioButton[K] } & { [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes as `attr:${K}`]?: ScxRadioButtonAttributes[K] } & { [K in keyof ScxRadioButton & keyof ScxRadioButtonAttributes as `prop:${K}`]?: ScxRadioButton[K] };
        "scx-radio-group": Omit<ScxRadioGroup, keyof ScxRadioGroupAttributes> & { [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes]?: ScxRadioGroup[K] } & { [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes as `attr:${K}`]?: ScxRadioGroupAttributes[K] } & { [K in keyof ScxRadioGroup & keyof ScxRadioGroupAttributes as `prop:${K}`]?: ScxRadioGroup[K] };
        "scx-root": Omit<ScxRoot, keyof ScxRootAttributes> & { [K in keyof ScxRoot & keyof ScxRootAttributes]?: ScxRoot[K] } & { [K in keyof ScxRoot & keyof ScxRootAttributes as `attr:${K}`]?: ScxRootAttributes[K] } & { [K in keyof ScxRoot & keyof ScxRootAttributes as `prop:${K}`]?: ScxRoot[K] };
        "scx-tabulator-example": ScxTabulatorExample;
        "smilecx-outbound-manager": SmilecxOutboundManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-model": LocalJSX.IntrinsicElements["add-model"] & JSXBase.HTMLAttributes<HTMLAddModelElement>;
            "add-score": LocalJSX.IntrinsicElements["add-score"] & JSXBase.HTMLAttributes<HTMLAddScoreElement>;
            "movable-rows-table": LocalJSX.IntrinsicElements["movable-rows-table"] & JSXBase.HTMLAttributes<HTMLMovableRowsTableElement>;
            "score-field": LocalJSX.IntrinsicElements["score-field"] & JSXBase.HTMLAttributes<HTMLScoreFieldElement>;
            "score-panel": LocalJSX.IntrinsicElements["score-panel"] & JSXBase.HTMLAttributes<HTMLScorePanelElement>;
            "scx-empty-state": LocalJSX.IntrinsicElements["scx-empty-state"] & JSXBase.HTMLAttributes<HTMLScxEmptyStateElement>;
            /**
             * Example Components Showcase
             * Dynamic tab-based documentation component using Shoelace tabs.
             * Features:
             * - Shoelace sl-tab-group for native tab UI
             * - Easy to add new components (just add to tabs array)
             * - Live interactive examples
             * - Code snippets with syntax highlighting
             * - API documentation tables
             * Adding a new component:
             * 1. Add new object to `tabs` array in componentWillLoad()
             * 2. Create render method for content
             * 3. Done! Tab is automatically rendered
             * Usage:
             * ```html
             * <scx-example-components></scx-example-components>
             * ```
             */
            "scx-example-components": LocalJSX.IntrinsicElements["scx-example-components"] & JSXBase.HTMLAttributes<HTMLScxExampleComponentsElement>;
            "scx-icons-example": LocalJSX.IntrinsicElements["scx-icons-example"] & JSXBase.HTMLAttributes<HTMLScxIconsExampleElement>;
            /**
             * Example Modal Component
             * Demonstrates how to create a modal content component that works with the Modal Service.
             * Key Patterns:
             * - Receives `modal` prop from Modal Service
             * - Calls `modal.close()` with appropriate data
             * - Uses confirm/dismiss flags to indicate user action
             * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
             * Usage:
             * ```typescript
             * import { starter } from '../../di/containers';
             * const modal = starter.modal;
             * modal.create({
             *   component: 'scx-example-modal',
             *   width: '500px',
             *   dismissOnEsc: true,
             *   backdropDismiss: true,
             *   componentProps: {
             *     modalTitle: 'Confirm Action',
             *     message: 'Are you sure you want to proceed?'
             *   }
             * });
             * modal.onDismiss((data) => {
             *   if (data.confirm) {
             *     console.log('User confirmed');
             *   } else {
             *     console.log('User cancelled');
             *   }
             * });
             * modal.show();
             * ```
             */
            "scx-modal-example": LocalJSX.IntrinsicElements["scx-modal-example"] & JSXBase.HTMLAttributes<HTMLScxModalExampleElement>;
            "scx-radio-button": LocalJSX.IntrinsicElements["scx-radio-button"] & JSXBase.HTMLAttributes<HTMLScxRadioButtonElement>;
            "scx-radio-group": LocalJSX.IntrinsicElements["scx-radio-group"] & JSXBase.HTMLAttributes<HTMLScxRadioGroupElement>;
            "scx-root": LocalJSX.IntrinsicElements["scx-root"] & JSXBase.HTMLAttributes<HTMLScxRootElement>;
            /**
             * Tabulator Example Component
             * Demonstrates how to use Tabulator with custom styling and sorting.
             * Features:
             * - Custom theme using tabulator-theme mixin
             * - Sortable columns (click headers)
             * - Movable rows (drag and drop)
             * - Sample data with multiple types
             * - Responsive layout
             * - Pagination
             * Usage:
             * ```html
             * <scx-tabulator-example></scx-tabulator-example>
             * ```
             */
            "scx-tabulator-example": LocalJSX.IntrinsicElements["scx-tabulator-example"] & JSXBase.HTMLAttributes<HTMLScxTabulatorExampleElement>;
            /**
             * Outbound Manager Application Component
             * Demonstrates core patterns for SmileCX applications:
             * - Service access via container getter (NOT
             * @Prop injection)
             * - Reactive state with BehaviorSubject subscriptions
             * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
             * - Event handlers for user interactions
             * - i18n with tt() function
             * This component is the reference implementation for external developers
             * building their own SmileCX-compatible applications.
             * Pattern: Application layer (business logic + UI)
             */
            "smilecx-outbound-manager": LocalJSX.IntrinsicElements["smilecx-outbound-manager"] & JSXBase.HTMLAttributes<HTMLSmilecxOutboundManagerElement>;
        }
    }
}
