/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface ScxRoot {
        /**
          * API base URL for backend requests Passed to container during initialization
          * @example // Development api-url="http://localhost:3001/t/acme-corp/v1"
          * @example // Production api-url="https://api.smilecx.com/t/acme-corp/v1"
          * @default ''
         */
        "apiUrl": string;
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }
}
declare global {
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface HTMLScxRootElement extends Components.ScxRoot, HTMLStencilElement {
    }
    var HTMLScxRootElement: {
        prototype: HTMLScxRootElement;
        new (): HTMLScxRootElement;
    };
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface HTMLSmilecxOutboundManagerElement extends Components.SmilecxOutboundManager, HTMLStencilElement {
    }
    var HTMLSmilecxOutboundManagerElement: {
        prototype: HTMLSmilecxOutboundManagerElement;
        new (): HTMLSmilecxOutboundManagerElement;
    };
    interface HTMLElementTagNameMap {
        "scx-root": HTMLScxRootElement;
        "smilecx-outbound-manager": HTMLSmilecxOutboundManagerElement;
    }
}
declare namespace LocalJSX {
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface ScxRoot {
        /**
          * API base URL for backend requests Passed to container during initialization
          * @example // Development api-url="http://localhost:3001/t/acme-corp/v1"
          * @example // Production api-url="https://api.smilecx.com/t/acme-corp/v1"
          * @default ''
         */
        "apiUrl"?: string;
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }
    interface IntrinsicElements {
        "scx-root": ScxRoot;
        "smilecx-outbound-manager": SmilecxOutboundManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Root Component (Application Shell)
             * Responsibilities:
             * - Initialize DI container with runtime config (API base URL)
             * - Render loading state during initialization
             * - Mount application component(s) after initialization
             * **IMPORTANT**: This component handles ONLY container initialization.
             * No business logic, no service usage, no subscriptions.
             * Application logic belongs in app components (smilecx-outbound-manager, etc.)
             * Pattern: Shell layer (init) vs Application layer (business logic)
             * Usage:
             * ```html
             * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
             * ```
             */
            "scx-root": LocalJSX.ScxRoot & JSXBase.HTMLAttributes<HTMLScxRootElement>;
            /**
             * Outbound Manager Application Component
             * Demonstrates core patterns for SmileCX applications:
             * - Service access via container getter (NOT
             * @Prop injection)
             * - Reactive state with BehaviorSubject subscriptions
             * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
             * - Event handlers for user interactions
             * - i18n with tt() function
             * This component is the reference implementation for external developers
             * building their own SmileCX-compatible applications.
             * Pattern: Application layer (business logic + UI)
             */
            "smilecx-outbound-manager": LocalJSX.SmilecxOutboundManager & JSXBase.HTMLAttributes<HTMLSmilecxOutboundManagerElement>;
        }
    }
}
