/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IModal } from "./libs/modal";
import { StyleEventDetail } from "./shared/scx-radio-group/scx-radio-button/scx-radio-button";
import { RadioGroupChangeEventDetail } from "./shared/scx-radio-group/scx-radio-group";
export { IModal } from "./libs/modal";
export { StyleEventDetail } from "./shared/scx-radio-group/scx-radio-button/scx-radio-button";
export { RadioGroupChangeEventDetail } from "./shared/scx-radio-group/scx-radio-group";
export namespace Components {
    interface ScxEmptyState {
        "esTitle"?: string;
        "icon": string;
        "label"?: string;
    }
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface ScxExampleComponents {
    }
    interface ScxIconsExample {
    }
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface ScxModalExample {
        /**
          * Modal message (optional) Passed via componentProps
          * @default 'This is an example modal component.'
         */
        "message": string;
        /**
          * Modal service reference Automatically injected by Modal Service
         */
        "modal": IModal;
        /**
          * Modal title (optional) Passed via componentProps
          * @default 'Example Modal'
         */
        "modalTitle": string;
    }
    interface ScxRadioButton {
        /**
          * If `true`, the radio is selected.
          * @default false
         */
        "checked": boolean;
        /**
          * If `true`, the user cannot interact with the radio.
          * @default false
         */
        "disabled": boolean;
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name": string;
        /**
          * The size of the radio button.
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The value of the radio button.
         */
        "value"?: unknown;
        /**
          * The color variant of the radio button.
          * @default 'default'
         */
        "variant": 'default' | 'neutral' | 'light';
    }
    interface ScxRadioGroup {
        /**
          * If `true`, the radios can be deselected.
          * @default false
         */
        "allowEmptySelection": boolean;
        /**
          * The size variant of the radio group. With hug each button accords its size to its content.
          * @default 'fill'
         */
        "contain": 'fill' | 'hug';
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name": string;
        /**
          * The size of the radio buttons.
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The value of the radio group.
         */
        "value"?: unknown | null;
        /**
          * The color variant of the radio group.
          * @default 'default'
         */
        "variant": 'default' | 'neutral' | 'light';
    }
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface ScxRoot {
        /**
          * API base URL for backend requests Passed to container during initialization
          * @example // Development api-url="http://localhost:3001/t/acme-corp/v1"
          * @example // Production api-url="https://api.smilecx.com/t/acme-corp/v1"
          * @default ''
         */
        "apiUrl": string;
    }
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface ScxTabulatorExample {
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }
}
export interface ScxRadioButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScxRadioButtonElement;
}
export interface ScxRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScxRadioGroupElement;
}
declare global {
    interface HTMLScxEmptyStateElement extends Components.ScxEmptyState, HTMLStencilElement {
    }
    var HTMLScxEmptyStateElement: {
        prototype: HTMLScxEmptyStateElement;
        new (): HTMLScxEmptyStateElement;
    };
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface HTMLScxExampleComponentsElement extends Components.ScxExampleComponents, HTMLStencilElement {
    }
    var HTMLScxExampleComponentsElement: {
        prototype: HTMLScxExampleComponentsElement;
        new (): HTMLScxExampleComponentsElement;
    };
    interface HTMLScxIconsExampleElement extends Components.ScxIconsExample, HTMLStencilElement {
    }
    var HTMLScxIconsExampleElement: {
        prototype: HTMLScxIconsExampleElement;
        new (): HTMLScxIconsExampleElement;
    };
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface HTMLScxModalExampleElement extends Components.ScxModalExample, HTMLStencilElement {
    }
    var HTMLScxModalExampleElement: {
        prototype: HTMLScxModalExampleElement;
        new (): HTMLScxModalExampleElement;
    };
    interface HTMLScxRadioButtonElementEventMap {
        "smStyle": StyleEventDetail;
        "smSelect": { checked: boolean; value: unknown };
        "smDeselect": void;
        "smFocus": void;
        "smBlur": void;
    }
    interface HTMLScxRadioButtonElement extends Components.ScxRadioButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(type: K, listener: (this: HTMLScxRadioButtonElement, ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScxRadioButtonElementEventMap>(type: K, listener: (this: HTMLScxRadioButtonElement, ev: ScxRadioButtonCustomEvent<HTMLScxRadioButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScxRadioButtonElement: {
        prototype: HTMLScxRadioButtonElement;
        new (): HTMLScxRadioButtonElement;
    };
    interface HTMLScxRadioGroupElementEventMap {
        "smChange": RadioGroupChangeEventDetail;
    }
    interface HTMLScxRadioGroupElement extends Components.ScxRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(type: K, listener: (this: HTMLScxRadioGroupElement, ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScxRadioGroupElementEventMap>(type: K, listener: (this: HTMLScxRadioGroupElement, ev: ScxRadioGroupCustomEvent<HTMLScxRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScxRadioGroupElement: {
        prototype: HTMLScxRadioGroupElement;
        new (): HTMLScxRadioGroupElement;
    };
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface HTMLScxRootElement extends Components.ScxRoot, HTMLStencilElement {
    }
    var HTMLScxRootElement: {
        prototype: HTMLScxRootElement;
        new (): HTMLScxRootElement;
    };
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface HTMLScxTabulatorExampleElement extends Components.ScxTabulatorExample, HTMLStencilElement {
    }
    var HTMLScxTabulatorExampleElement: {
        prototype: HTMLScxTabulatorExampleElement;
        new (): HTMLScxTabulatorExampleElement;
    };
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface HTMLSmilecxOutboundManagerElement extends Components.SmilecxOutboundManager, HTMLStencilElement {
    }
    var HTMLSmilecxOutboundManagerElement: {
        prototype: HTMLSmilecxOutboundManagerElement;
        new (): HTMLSmilecxOutboundManagerElement;
    };
    interface HTMLElementTagNameMap {
        "scx-empty-state": HTMLScxEmptyStateElement;
        "scx-example-components": HTMLScxExampleComponentsElement;
        "scx-icons-example": HTMLScxIconsExampleElement;
        "scx-modal-example": HTMLScxModalExampleElement;
        "scx-radio-button": HTMLScxRadioButtonElement;
        "scx-radio-group": HTMLScxRadioGroupElement;
        "scx-root": HTMLScxRootElement;
        "scx-tabulator-example": HTMLScxTabulatorExampleElement;
        "smilecx-outbound-manager": HTMLSmilecxOutboundManagerElement;
    }
}
declare namespace LocalJSX {
    interface ScxEmptyState {
        "esTitle"?: string;
        "icon": string;
        "label"?: string;
    }
    /**
     * Example Components Showcase
     * Dynamic tab-based documentation component using Shoelace tabs.
     * Features:
     * - Shoelace sl-tab-group for native tab UI
     * - Easy to add new components (just add to tabs array)
     * - Live interactive examples
     * - Code snippets with syntax highlighting
     * - API documentation tables
     * Adding a new component:
     * 1. Add new object to `tabs` array in componentWillLoad()
     * 2. Create render method for content
     * 3. Done! Tab is automatically rendered
     * Usage:
     * ```html
     * <scx-example-components></scx-example-components>
     * ```
     */
    interface ScxExampleComponents {
    }
    interface ScxIconsExample {
    }
    /**
     * Example Modal Component
     * Demonstrates how to create a modal content component that works with the Modal Service.
     * Key Patterns:
     * - Receives `modal` prop from Modal Service
     * - Calls `modal.close()` with appropriate data
     * - Uses confirm/dismiss flags to indicate user action
     * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
     * Usage:
     * ```typescript
     * import { starter } from '../../di/containers';
     * const modal = starter.modal;
     * modal.create({
     *   component: 'scx-example-modal',
     *   width: '500px',
     *   dismissOnEsc: true,
     *   backdropDismiss: true,
     *   componentProps: {
     *     modalTitle: 'Confirm Action',
     *     message: 'Are you sure you want to proceed?'
     *   }
     * });
     * modal.onDismiss((data) => {
     *   if (data.confirm) {
     *     console.log('User confirmed');
     *   } else {
     *     console.log('User cancelled');
     *   }
     * });
     * modal.show();
     * ```
     */
    interface ScxModalExample {
        /**
          * Modal message (optional) Passed via componentProps
          * @default 'This is an example modal component.'
         */
        "message"?: string;
        /**
          * Modal service reference Automatically injected by Modal Service
         */
        "modal": IModal;
        /**
          * Modal title (optional) Passed via componentProps
          * @default 'Example Modal'
         */
        "modalTitle"?: string;
    }
    interface ScxRadioButton {
        /**
          * If `true`, the radio is selected.
          * @default false
         */
        "checked"?: boolean;
        /**
          * If `true`, the user cannot interact with the radio.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name"?: string;
        /**
          * Emitted when the radio button loses focus.
         */
        "onSmBlur"?: (event: ScxRadioButtonCustomEvent<void>) => void;
        /**
          * Emitted when a checked radio button is deselected.
         */
        "onSmDeselect"?: (event: ScxRadioButtonCustomEvent<void>) => void;
        /**
          * Emitted when the radio button gains focus.
         */
        "onSmFocus"?: (event: ScxRadioButtonCustomEvent<void>) => void;
        /**
          * Emitted when the radio button is selected.
         */
        "onSmSelect"?: (event: ScxRadioButtonCustomEvent<{ checked: boolean; value: unknown }>) => void;
        /**
          * Emitted when the styles change.
         */
        "onSmStyle"?: (event: ScxRadioButtonCustomEvent<StyleEventDetail>) => void;
        /**
          * The size of the radio button.
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The value of the radio button.
         */
        "value"?: unknown;
        /**
          * The color variant of the radio button.
          * @default 'default'
         */
        "variant"?: 'default' | 'neutral' | 'light';
    }
    interface ScxRadioGroup {
        /**
          * If `true`, the radios can be deselected.
          * @default false
         */
        "allowEmptySelection"?: boolean;
        /**
          * The size variant of the radio group. With hug each button accords its size to its content.
          * @default 'fill'
         */
        "contain"?: 'fill' | 'hug';
        /**
          * The name of the control, which is submitted with the form data.
          * @default this.inputId
         */
        "name"?: string;
        /**
          * Emitted when the value has changed.
         */
        "onSmChange"?: (event: ScxRadioGroupCustomEvent<RadioGroupChangeEventDetail>) => void;
        /**
          * The size of the radio buttons.
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The value of the radio group.
         */
        "value"?: unknown | null;
        /**
          * The color variant of the radio group.
          * @default 'default'
         */
        "variant"?: 'default' | 'neutral' | 'light';
    }
    /**
     * Root Component (Application Shell)
     * Responsibilities:
     * - Initialize DI container with runtime config (API base URL)
     * - Render loading state during initialization
     * - Mount application component(s) after initialization
     * **IMPORTANT**: This component handles ONLY container initialization.
     * No business logic, no service usage, no subscriptions.
     * Application logic belongs in app components (smilecx-outbound-manager, etc.)
     * Pattern: Shell layer (init) vs Application layer (business logic)
     * Usage:
     * ```html
     * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
     * ```
     */
    interface ScxRoot {
        /**
          * API base URL for backend requests Passed to container during initialization
          * @example // Development api-url="http://localhost:3001/t/acme-corp/v1"
          * @example // Production api-url="https://api.smilecx.com/t/acme-corp/v1"
          * @default ''
         */
        "apiUrl"?: string;
    }
    /**
     * Tabulator Example Component
     * Demonstrates how to use Tabulator with custom styling and sorting.
     * Features:
     * - Custom theme using tabulator-theme mixin
     * - Sortable columns (click headers)
     * - Movable rows (drag and drop)
     * - Sample data with multiple types
     * - Responsive layout
     * - Pagination
     * Usage:
     * ```html
     * <scx-tabulator-example></scx-tabulator-example>
     * ```
     */
    interface ScxTabulatorExample {
    }
    /**
     * Outbound Manager Application Component
     * Demonstrates core patterns for SmileCX applications:
     * - Service access via container getter (NOT
     * @Prop injection)
     * - Reactive state with BehaviorSubject subscriptions
     * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
     * - Event handlers for user interactions
     * - i18n with tt() function
     * This component is the reference implementation for external developers
     * building their own SmileCX-compatible applications.
     * Pattern: Application layer (business logic + UI)
     */
    interface SmilecxOutboundManager {
    }
    interface IntrinsicElements {
        "scx-empty-state": ScxEmptyState;
        "scx-example-components": ScxExampleComponents;
        "scx-icons-example": ScxIconsExample;
        "scx-modal-example": ScxModalExample;
        "scx-radio-button": ScxRadioButton;
        "scx-radio-group": ScxRadioGroup;
        "scx-root": ScxRoot;
        "scx-tabulator-example": ScxTabulatorExample;
        "smilecx-outbound-manager": SmilecxOutboundManager;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scx-empty-state": LocalJSX.ScxEmptyState & JSXBase.HTMLAttributes<HTMLScxEmptyStateElement>;
            /**
             * Example Components Showcase
             * Dynamic tab-based documentation component using Shoelace tabs.
             * Features:
             * - Shoelace sl-tab-group for native tab UI
             * - Easy to add new components (just add to tabs array)
             * - Live interactive examples
             * - Code snippets with syntax highlighting
             * - API documentation tables
             * Adding a new component:
             * 1. Add new object to `tabs` array in componentWillLoad()
             * 2. Create render method for content
             * 3. Done! Tab is automatically rendered
             * Usage:
             * ```html
             * <scx-example-components></scx-example-components>
             * ```
             */
            "scx-example-components": LocalJSX.ScxExampleComponents & JSXBase.HTMLAttributes<HTMLScxExampleComponentsElement>;
            "scx-icons-example": LocalJSX.ScxIconsExample & JSXBase.HTMLAttributes<HTMLScxIconsExampleElement>;
            /**
             * Example Modal Component
             * Demonstrates how to create a modal content component that works with the Modal Service.
             * Key Patterns:
             * - Receives `modal` prop from Modal Service
             * - Calls `modal.close()` with appropriate data
             * - Uses confirm/dismiss flags to indicate user action
             * - Follows standard modal structure with modal-wrapper, modal-head, modal-content, modal-footer
             * Usage:
             * ```typescript
             * import { starter } from '../../di/containers';
             * const modal = starter.modal;
             * modal.create({
             *   component: 'scx-example-modal',
             *   width: '500px',
             *   dismissOnEsc: true,
             *   backdropDismiss: true,
             *   componentProps: {
             *     modalTitle: 'Confirm Action',
             *     message: 'Are you sure you want to proceed?'
             *   }
             * });
             * modal.onDismiss((data) => {
             *   if (data.confirm) {
             *     console.log('User confirmed');
             *   } else {
             *     console.log('User cancelled');
             *   }
             * });
             * modal.show();
             * ```
             */
            "scx-modal-example": LocalJSX.ScxModalExample & JSXBase.HTMLAttributes<HTMLScxModalExampleElement>;
            "scx-radio-button": LocalJSX.ScxRadioButton & JSXBase.HTMLAttributes<HTMLScxRadioButtonElement>;
            "scx-radio-group": LocalJSX.ScxRadioGroup & JSXBase.HTMLAttributes<HTMLScxRadioGroupElement>;
            /**
             * Root Component (Application Shell)
             * Responsibilities:
             * - Initialize DI container with runtime config (API base URL)
             * - Render loading state during initialization
             * - Mount application component(s) after initialization
             * **IMPORTANT**: This component handles ONLY container initialization.
             * No business logic, no service usage, no subscriptions.
             * Application logic belongs in app components (smilecx-outbound-manager, etc.)
             * Pattern: Shell layer (init) vs Application layer (business logic)
             * Usage:
             * ```html
             * <scx-root api-url="http://localhost:3001/t/acme-corp/v1"></scx-root>
             * ```
             */
            "scx-root": LocalJSX.ScxRoot & JSXBase.HTMLAttributes<HTMLScxRootElement>;
            /**
             * Tabulator Example Component
             * Demonstrates how to use Tabulator with custom styling and sorting.
             * Features:
             * - Custom theme using tabulator-theme mixin
             * - Sortable columns (click headers)
             * - Movable rows (drag and drop)
             * - Sample data with multiple types
             * - Responsive layout
             * - Pagination
             * Usage:
             * ```html
             * <scx-tabulator-example></scx-tabulator-example>
             * ```
             */
            "scx-tabulator-example": LocalJSX.ScxTabulatorExample & JSXBase.HTMLAttributes<HTMLScxTabulatorExampleElement>;
            /**
             * Outbound Manager Application Component
             * Demonstrates core patterns for SmileCX applications:
             * - Service access via container getter (NOT
             * @Prop injection)
             * - Reactive state with BehaviorSubject subscriptions
             * - Lifecycle management (subscribe in componentWillLoad, unsubscribe in disconnectedCallback)
             * - Event handlers for user interactions
             * - i18n with tt() function
             * This component is the reference implementation for external developers
             * building their own SmileCX-compatible applications.
             * Pattern: Application layer (business logic + UI)
             */
            "smilecx-outbound-manager": LocalJSX.SmilecxOutboundManager & JSXBase.HTMLAttributes<HTMLSmilecxOutboundManagerElement>;
        }
    }
}
